/*
 * EXT_INT_CFG.h
 *
 * Created: 4/21/2021 11:41:47 PM
 *  Author: Rateb
 */ 


#ifndef EXT_INT_CFG_H_
#define EXT_INT_CFG_H_

#define GLOBAL_INTERRUPT    GLOBAL_INTERRUPT_ENABLE
#define EXT_INT0_TRIGGER    TRIGGER_ANY_LOGICAL_CHANGE
#define EXT_INT1_TRIGGER    TRIGGER_FALLING
#define EXT_INT2_TRIGGER    TRIGGER_RISING




#endif /* EXT_INT_CFG_H_ */